runtime: nodejs18
entrypoint: npm start

env_variables:
  # DATABASE_URL: "mysql://ed:1234@/intuitive_planner_dev?unix_socket=/cloudsql/intuitiveplanner:us-east4:intuitive-planner-db"
  DATABASE_URL: "postgresql://neondb_owner:npg_bhUJ0qeNWy5I@ep-misty-lake-a5o6ldl6-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"

manual_scaling:
  instances: 1
